# Generated by Django 4.1.1 on 2022-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(default='exit', upload_to=None),
            preserve_default=False,
        ),
    ]
